name: 'Build Tauri App'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./app

      - name: Build Tauri app
        run: npm run tauri build -- --verbose
        working-directory: ./app
