name: 'Build Tauri App'

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  build-tauri:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./app

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./app
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseDraft: true
          prerelease: false
          args: -- --verbose
